### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by sg-first** [mthom/on-the-fly-gc#1]
Hello, I want to learn the project. Is there document that lets me know how to use it?

**Comment by mthom** [comment]
Thanks for you interest!

I created the [managed-ctrie](http://github.com/mthom/managed-ctrie) repository as a demo/reference for how a client would interface with OTF.  

Most of the parts of interest are in https://github.com/mthom/managed-ctrie/blob/master/include/. These are fairly straightforward -- the tracer is used during the mark phase to mark live objects, the destroy_type* functions are called to deinitialize objects before destruction, the string and vector types have example allocators that call out to the GC, etc.

Some features -- like log pointers -- are more obscure and will probably require you to read the paper.

**Comment by sg-first** [comment]
Thank you. I'll try to read it.
